{
  "openapi": "3.0.1",
  "info": {
    "description": "SumUp’s REST API operates with `application/json` HTTP requests and response. The request bodies are sent through resource-oriented URLs and use the standard HTTP response codes.\n\nFor testing our APIs, please <a href='https://cloud.crm.sumup.com/sumup-developers-contact-form'>contact us</a> for a test account. \n\nWhen you receive your test account you can create your <a href='https://developer.sumup.com/docs/register-app/#3-create-oauth-client-credentials' target='_blank'>[...]",
    "title": "SumUp REST API",
    "version": "1.0.0"
  },
  "servers": [
    {
      "description": "Production server",
      "url": "https://api.sumup.com/{version}",
      "variables": {
        "version": {
          "default": "v0.1",
          "description": "Version of the API.",
          "enum": [
            "v0.1",
            "v1.0"
          ]
        }
      }
    }
  ],
  "paths": {
    "/authorize": {
      "get": {
        "summary": "Request authorization from users",
        "description": "Request authorization from users and grant your application access to resources associated with the user's account.\n",
        "servers": [
          {
            "url": "https://api.sumup.com/"
          }
        ],
        "tags": [
          "Authorization"
        ]
      }
    },
    "/checkouts": {
      "get": {
        "summary": "List checkouts",
        "description": "Lists created checkout resources according to the applied `checkout_reference`.",
        "security": [
          {
            "accessToken": [
              "payments"
            ]
          }
        ],
        "tags": [
          "Checkouts"
        ]
      },
      "post": {
        "summary": "Create a checkout",
        "description": "Creates a new payment checkout resource. The unique `checkout_reference` created by this request, is used for further manipulation of the checkout. \n\nFor 3DS checkouts, add the `redirect_url` parameter to your request body schema.\n\nFollow by processing a checkout to charge the provided payment instrument.\n",
        "security": [
          {
            "accessToken": [
              "payments"
            ]
          }
        ],
        "tags": [
          "Checkouts"
        ]
      }
    },
    "/checkouts/{id}": {
      "delete": {
        "summary": "Deactivate a checkout",
        "description": "Deactivates an identified checkout resource. If the checkout has already been processed it can not be deactivated.",
        "security": [
          {
            "accessToken": [
              "payments"
            ]
          }
        ],
        "tags": [
          "Checkouts"
        ]
      },
      "get": {
        "summary": "Retrieve a checkout",
        "description": "Retrieves an identified checkout resource. Use this request after processing a checkout to confirm its status and inform the end user respectively.",
        "security": [
          {
            "accessToken": [
              "payments"
            ]
          }
        ],
        "tags": [
          "Checkouts"
        ]
      },
      "put": {
        "summary": "Process a checkout",
        "description": "Processing a checkout will attempt to charge the provided payment instrument for the amount of the specified checkout resource initiated in the `Create a checkout` endpoint.\n\nFollow this request with `Retrieve a checkout` to confirm its status.\n",
        "tags": [
          "Checkouts"
        ]
      }
    },
    "/customers": {
      "post": {
        "summary": "Create a customer",
        "description": "Creates a new saved customer resource which you can later manipulate and save payment instruments to.",
        "security": [
          {
            "accessToken": [
              "payment_instruments"
            ]
          }
        ],
        "tags": [
          "Customers"
        ]
      }
    },
    "/customers/{customer_id}": {
      "get": {
        "summary": "Retrieve a customer",
        "description": "Retrieves an identified saved customer resource through the unique `customer_id` parameter, generated upon customer creation.",
        "security": [
          {
            "accessToken": [
              "payment_instruments"
            ]
          }
        ],
        "tags": [
          "Customers"
        ]
      },
      "put": {
        "summary": "Update a customer",
        "description": "Updates an identified saved customer resource's personal details. \n\nThe request only overwrites the parameters included in the request, all other parameters will remain with their initially assigned values.\n",
        "security": [
          {
            "accessToken": [
              "payment_instruments"
            ]
          }
        ],
        "tags": [
          "Customers"
        ]
      }
    },
    "/customers/{customer_id}/payment-instruments": {
      "get": {
        "summary": "List payment instruments",
        "description": "Lists all payment instrument resources that are saved for an identified customer.",
        "security": [
          {
            "accessToken": [
              "payment_instruments"
            ]
          }
        ],
        "tags": [
          "Customers"
        ]
      },
      "post": {
        "summary": "Create a payment instrument",
        "description": "Creates and activates a new payment instrument resource by saving a payment card for an identified customer. Implement to improve customer experience by skipping the step of entering payment instrument details.\n\nThe token created via this endpoint <b>can not</b> be used for recurring payments by merchants operating within the EU. For more information visit our <a href=\"https://developer.sumup.com/docs/recurring-payments/\" target=\"_blank\">recurring payments guide</a>[...]",
        "security": [
          {
            "accessToken": [
              "payment_instruments"
            ]
          }
        ],
        "tags": [
          "Customers"
        ]
      }
    },
    "/customers/{customer_id}/payment-instruments/{token}": {
      "delete": {
        "summary": "Deactivate a payment instrument",
        "description": "Deactivates an identified card payment instrument resource for a customer.",
        "security": [
          {
            "accessToken": [
              "payment_instruments"
            ]
          }
        ],
        "tags": [
          "Customers"
        ]
      }
    },
    "/me": {
      "get": {
        "summary": "Retrieve an account",
        "description": "Returns user account information.",
        "security": [
          {
            "accessToken": [
              "user.profile",
              "user.profile_readonly"
            ]
          }
        ],
        "tags": [
          "Account Details"
        ]
      }
    },
    "/me/accounts": {
      "get": {
        "summary": "List subaccounts",
        "security": [
          {
            "accessToken": [
              "user.subaccounts"
            ]
          }
        ],
        "tags": [
          "Subaccounts"
        ]
      },
      "post": {
        "summary": "Create a subaccount",
        "security": [
          {
            "accessToken": [
              "user.subaccounts"
            ]
          }
        ],
        "tags": [
          "Subaccounts"
        ]
      }
    },
    "/me/accounts/{operator_code}": {
      "delete": {
        "summary": "Deactivate a subaccount",
        "security": [
          {
            "accessToken": [
              "user.subaccounts"
            ]
          }
        ],
        "tags": [
          "Subaccounts"
        ]
      },
      "put": {
        "summary": "Update a subaccount",
        "security": [
          {
            "accessToken": [
              "user.subaccounts"
            ]
          }
        ],
        "tags": [
          "Subaccounts"
        ]
      }
    },
    "/me/financials/payouts": {
      "get": {
        "summary": "List payouts",
        "description": "Lists ordered payouts for the merchant account.",
        "security": [
          {
            "accessToken": [
              "user.profile",
              "user.profile_readonly"
            ]
          }
        ],
        "tags": [
          "Payouts"
        ]
      }
    },
    "/me/financials/transactions": {
      "get": {
        "summary": "List transactions",
        "description": "Lists a less detailed history of all transactions associated with the merchant account.",
        "security": [
          {
            "accessToken": [
              "user.profile",
              "user.profile_readonly"
            ]
          }
        ],
        "tags": [
          "Payouts"
        ]
      }
    },
    "/me/merchant-profile": {
      "get": {
        "summary": "Retrieve a profile",
        "description": "Retrieves merchant profile data.",
        "security": [
          {
            "accessToken": [
              "user.profile",
              "user.profile_readonly"
            ]
          }
        ],
        "tags": [
          "Merchant Account"
        ]
      }
    },
    "/me/merchant-profile/bank-accounts": {
      "get": {
        "summary": "List bank accounts",
        "description": "Retrives bank accounts of the merchant.",
        "security": [
          {
            "accessToken": [
              "user.payout-settings",
              "user.profile",
              "user.profile_readonly"
            ]
          }
        ],
        "tags": [
          "Merchant Account"
        ]
      }
    },
    "/me/merchant-profile/doing-business-as": {
      "get": {
        "summary": "Retrieve DBA",
        "description": "Retrieves Doing Business As profile.",
        "security": [
          {
            "accessToken": [
              "user.profile",
              "user.profile_readonly"
            ]
          }
        ],
        "tags": [
          "Merchant Account"
        ]
      }
    },
    "/me/merchant-profile/settings": {
      "get": {
        "summary": "List settings",
        "description": "Retrieves merchant settings.",
        "security": [
          {
            "accessToken": [
              "user.payout-settings"
            ]
          }
        ],
        "tags": [
          "Merchant Account"
        ]
      }
    },
    "/me/personal-profile": {
      "get": {
        "summary": "Retrieve a profile",
        "description": "Retrives personal profile data.",
        "security": [
          {
            "accessToken": [
              "user.profile",
              "user.profile_readonly"
            ]
          }
        ],
        "tags": [
          "Personal Account"
        ]
      }
    },
    "/me/refund/{txn_id}": {
      "post": {
        "summary": "Refund a transaction",
        "description": "Refunds an identified transaction either in full or partially.",
        "security": [
          {
            "accessToken": [
              "payments"
            ]
          }
        ],
        "tags": [
          "Refunds"
        ]
      }
    },
    "/me/transactions": {
      "get": {
        "summary": "Retrieve a transaction",
        "description": "Retrieves the full details of an identified transaction. The transaction resource is identified by a query parameter and *one* of following parameters is required:\n *  `id`\n *  `internal_id`\n *  `transaction_code`\n *  `foreign_transaction_id`\n *  `client_transaction_id`\n",
        "security": [
          {
            "accessToken": [
              "transactions.history"
            ]
          }
        ],
        "tags": [
          "Transactions"
        ]
      }
    },
    "/me/transactions/history": {
      "get": {
        "summary": "List transactions",
        "description": "Lists detailed history of all transactions associated with the merchant account.",
        "security": [
          {
            "accessToken": [
              "transactions.history"
            ]
          }
        ],
        "tags": [
          "Transactions"
        ]
      }
    },
    "/receipts/{id}": {
      "get": {
        "summary": "Retrieve receipt details",
        "description": "Retrieves receipt specific data for a transaction.",
        "security": [
          {
            "accessToken": []
          }
        ],
        "servers": [
          {
            "url": "https://api.sumup.com/v1.0"
          }
        ],
        "tags": [
          "Receipts"
        ]
      }
    },
    "/token": {
      "post": {
        "summary": "Generate a token",
        "description": "Generate a token or a refresh token\n",
        "servers": [
          {
            "url": "https://api.sumup.com/"
          }
        ],
        "tags": [
          "Authorization"
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "accessToken": {
        "description": "At SumUp authentication uses your API credentials and Basic HTTP auth. The API credentials consist of a `client_id` and `client_secret` key-value pair.\n\nIt is possible to create multiple API credentials for each of the applications you connect with your SumUp account.\n\nUse the API credentials as an authorization header for requests that require such.\n\nAuthorization\n---------\n\nSumUp uses the <a href='https://tools.ietf.org/html/rfc6749' target='_blank'>OAuth 2.0 a[...]",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://api.sumup.com/authorize",
            "refreshUrl": "https://api.sumup.com/token",
            "scopes": {
              "payment_instruments": "Manage customers and their payment instruments.",
              "payments": "Make payments by creating and processing checkouts.",
              "transactions.history": "View transactions and transaction history.",
              "user.app-settings": "View and manage the SumUp mobile application settings.",
              "user.payout-settings": "View and manage your payout settings.",
              "user.profile": "View and manage your user profile.",
              "user.profile_readonly": "View user profile details.",
              "user.subaccounts": "View and manage the user profile details of your employees."
            },
            "tokenUrl": "https://api.sumup.com/token"
          },
          "clientCredentials": {
            "scopes": {
              "payment_instruments": "Manage customers and their payment instruments.",
              "payments": "Make payments by creating and processing checkouts.",
              "transactions.history": "View transactions and transaction history.",
              "user.app-settings": "View and manage the SumUp mobile application settings.",
              "user.payout-settings": "View and manage your payout settings.",
              "user.profile": "View and manage your user profile.",
              "user.profile_readonly": "View user profile details.",
              "user.subaccounts": "View and manage the user profile details of your employee."
            },
            "tokenUrl": "https://api.sumup.com/token"
          }
        },
        "type": "oauth2"
      }
    }
  },
  "tags": [
    {
      "description": "Retrieve access tokens to grant your application access to specific resources or generate refresh tokens for expired access tokens.\n",
      "name": "Authorization"
    },
    {
      "description": "Accept payments from your end users by adding the Checkouts model to your platform. \nSumUp supports standard and single payment 3DS checkout flows. \n\nThe Checkout model allows creating, listing, retrieving, processing and deactivating checkouts. \nA payment is completed by creating a checkout and then processing the checkout.\n",
      "name": "Checkouts"
    },
    {
      "description": "Allow your regular customers to save their information with the Customers model. \nThis will prevent re-entering payment instrument information for recurring payments on your platform. \n\nDepending on the needs you can allow, creating, listing or deactivating payment instruments & creating, retrieving and updating customers.\n",
      "name": "Customers"
    },
    {
      "description": "Retrieve details for a specific transaction by it’s `id` \nor any other required query parameter, or list all transactions related to the merchant account.\n",
      "name": "Transactions"
    },
    {
      "description": "The Payouts model will allow you to track funds you’ve received from SumUp. \nYou can receive a detailed payouts list with information like dates, fees, references and statuses, using the `List payouts` endpoint. \n\nFor a less detailed payouts list use `List transactions`.'\n",
      "name": "Payouts"
    },
    {
      "description": "The Refunds model allows you to process a refund by identifying it with its unique transaction id.",
      "name": "Refunds"
    },
    {
      "description": "The Receipts model obtains receipt-like details for specific transactions.",
      "name": "Receipts"
    },
    {
      "description": "Account Details.",
      "name": "Account Details"
    },
    {
      "description": "Personal Account.",
      "name": "Personal Account"
    },
    {
      "description": "Manage merchant account.",
      "name": "Merchant Account"
    },
    {
      "description": "Manage subaccounts.",
      "name": "Subaccounts"
    }
  ]
}